### ISSUE TITLE
Error when compileing 

### ISSUE THREAD

**Issue by dg7abl** [ADSBexchange/feedclient#1]
Installing mlat-client to virtual environment

34
36
38
40
46
48
50
60
Created symlink /etc/systemd/system/default.target.wants/adsbexchange-mlat.service → /lib/systemd/system/adsbexchange-mlat.service.
70

Compiling / installing the readsb based feed client

72
74
rm -f *.o uat2esnt/*.o compat/clock_gettime/*.o compat/clock_nanosleep/*.o readsb viewadsb cprtests crctests convert_benchmark
api.c: In function ‘apiReadRequest’:
api.c:1530:0: error: ignoring #pragma GCC unroll [-Werror=unknown-pragmas]
     _unroll_32
 
api.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-format-truncation’ [-Werror]
cc1: all warnings being treated as errors
make: *** [api.o] Fehler 1
make: *** Es wird auf noch nicht beendete Prozesse gewartet...
------------
[ERROR] Error in line 300 when executing: make -j2 AIRCRAFT_HASH_BITS=12 >> $LOGFILE

**Comment by wiedehopf** [comment]
Can you try again please.

Also note that your system is likely very old.

**Comment by dg7abl** [comment]
Thanks for the quick support , now it's running well. And yes it's old :)
