### ISSUE TITLE
How to remove feed to adsbexchange?

### ISSUE THREAD

**Issue by jdschuitemaker** [ADSBexchange/feedclient#4]
Given the recent story about ADSBexchange being sold to JetNet I have decided to remove the feed to ADSBexchange. Are there any instructions on how to remove/uninstall the feedclient?

**Comment by migliozziz** [comment]
All credit to SoylentADSB on Airframes.io discord (https://discord.gg/aXt7KdycJk) for bringing this to attention.

Message Link: https://discord.com/channels/546776636352364576/679818367908970556/1067844886784655473

>  Removal / disabling the services:  <br>
sudo bash /usr/local/share/adsbexchange/uninstall.sh  <br>
If the above doesn't work, you may be using an old version that didn't have the uninstall script, just disable the services and the scripts won't run anymore:<br>
sudo systemctl disable --now adsbexchange-feed
sudo systemctl disable --now adsbexchange-mlat

**Comment by wiedehopf** [comment]
Literally at the bottom of the readme for this github repo.
